##---------------------------------------------------##
# CUSTOM HYPRLAND CONFIGURATIONS (USERPREFS)
# ~/.config/hypr/conf/custom.conf
# Add your additional Hyprland configurations here
# 
# This is an example of an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }
##---------------------------------------------------##

# SDL version wayland
env = SDL_VIDEODRIVER,wayland
# SDL version X11
# env = SDL_VIDEODRIVER,x11

# Keyboard Toggle
$LAPTOP_KB_ENABLED = true
device {
	name = at-translated-set-2-keyboard
	enabled = $LAPTOP_KB_ENABLED
}
